### ISSUE TITLE
求教安装运行，如下日志如何解决

### ISSUE THREAD

**Issue by carozhu** [EasilyTest/stf#11]
在bin目录下执行：./stf local --public-ip 192.168.15.180
（node版本用8.x, 10.x , 11.x都试过）
报： 
YError: Invalid third argument. Expected string but received function.
    at argumentTypeError (/Users/caro/EasilyTest/stf/node_modules/yargs/build/index.cjs:163:11)
    at parsed.optional.forEach.optional (/Users/caro/EasilyTest/stf/node_modules/yargs/build/index.cjs:145:17)
    at Array.forEach (<anonymous>)
    at argsert (/Users/caro/EasilyTest/stf/node_modules/yargs/build/index.cjs:138:25)
    at Object.version (/Users/caro/EasilyTest/stf/node_modules/yargs/build/index.cjs:2501:9)
    at Object.<anonymous> (/Users/caro/EasilyTest/stf/lib/cli/index.js:45:4)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/caro/EasilyTest/stf/lib/cli/please.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
2021-04-28T00:02:44.990Z INF/util:procutil 83769 [*] Forking "/Users/caro/EasilyTest/stf/lib/cli migrate"
YError: Invalid third argument. Expected string but received function.
    at argumentTypeError (/Users/caro/EasilyTest/stf/node_modules/yargs/build/index.cjs:163:11)
    at parsed.optional.forEach.optional (/Users/caro/EasilyTest/stf/node_modules/yargs/build/index.cjs:145:17)
    at Array.forEach (<anonymous>)
    at argsert (/Users/caro/EasilyTest/stf/node_modules/yargs/build/index.cjs:138:25)
    at Object.version (/Users/caro/EasilyTest/stf/node_modules/yargs/build/index.cjs:2501:9)
    at Object.<anonymous> (/Users/caro/EasilyTest/stf/lib/cli/index.js:45:4)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
/Users/caro/EasilyTest/stf/node_modules/yargs/build/index.cjs:2772
                throw err;
                ^

TypeError: ProtoBuf.loadProtoFile is not a function
    at Object.<anonymous> (/Users/caro/EasilyTest/stf/lib/wire/index.js:5:21)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/caro/EasilyTest/stf/lib/wire/util.js:3:12)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/caro/EasilyTest/stf/lib/db/api.js:9:16)
    at Module._compile (internal/modules/cjs/loader.js:816:30)

/Users/caro/EasilyTest/stf/node_modules/bluebird/js/main/promise.js:680
            throw e;
            ^
ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/Users/caro/EasilyTest/stf/lib/util/procutil.js:49:23)
    at ChildProcess.emit (events.js:193:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)

**Comment by EasilyTest** [comment]
看样子是依赖没装，重新编译安装一下
