### ISSUE TITLE
stf 启动报错，doctor检查依赖没问题

### ISSUE THREAD

**Issue by arcfree** [EasilyTest/stf#12]
./stf doctor 检查没问题
2021-06-16T08:19:56.067Z INF/cli:doctor 164990 [*] OS Arch: x64
2021-06-16T08:19:56.069Z INF/cli:doctor 164990 [*] OS Platform: linux
2021-06-16T08:19:56.070Z INF/cli:doctor 164990 [*] OS Platform: 3.10.0-1160.21.1.el7.x86_64
2021-06-16T08:19:56.070Z INF/cli:doctor 164990 [*] Using Node 6.17.1
2021-06-16T08:19:56.098Z INF/cli:doctor 164990 [*] Using ZeroMQ 4.3.2
2021-06-16T08:19:56.123Z INF/cli:doctor 164990 [*] Using ADB 1.0.31
2021-06-16T08:19:56.124Z INF/cli:doctor 164990 [*] Using ProtoBuf 3.11.2
2021-06-16T08:19:56.125Z INF/cli:doctor 164990 [*] Using GraphicsMagick 1.3.34
2021-06-16T08:19:56.125Z INF/cli:doctor 164990 [*] Using RethinkDB 2.4.0

启动报错：./stf  local --public-ip 10.0.242.17
2021-06-16T08:15:59.041Z INF/db 164378 [*] Connecting to 127.0.0.1:28015
../lib/cli websocket

选项：
  -h, --help          Show help.                                          [布尔]
  -V, --version       Show version.                                       [布尔]
  --connect-push, -c  App-side ZeroMQ PULL endpoint to connect to. [数组] [必需]
  --connect-sub, -u   App-side ZeroMQ PUB endpoint to connect to.  [数组] [必需]
  --port, -p          The port to bind to.                 [数字] [默认值: 7110]
  --secret, -s        The secret to use for auth JSON Web Tokens. Anyone who
                      knows this token can freely enter the system if they want,
                      so keep it safe.                           [字符串] [必需]
  --ssid, -i          The name of the session ID cookie.
                                                       [字符串] [默认值: "ssid"]
  --storage-url, -r   URL to the storage unit.                   [字符串] [必需]

Each option can be be overwritten with an environment variable by converting the
option to uppercase, replacing dashes with underscores and prefixing it with
`STF_WEBSOCKET_` (e.g. `STF_WEBSOCKET_STORAGE_URL`).

Unexpected token ...
2021-06-16T08:15:59.114Z FTL/cli:local 164321 [*] Child process had an error ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/home/data/new-stf/stf/lib/util/procutil.js:49:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)

**Comment by liyinchigithub** [comment]
Node 6.17.1 版本过低 作者好像使用8.0的版本
