### ISSUE TITLE
npm install 安装失败

### ISSUE THREAD

**Issue by SuperChaoM** [EasilyTest/stf#14]
bower cached        https://github.com/angular/bower-angular.git#1.8.0
bower validate      1.8.0 against https://github.com/angular/bower-angular.git#>=1.2.1
bower ECMDERR       Failed to execute "git ls-remote --tags --heads https://github.com/chieffancypants/angular-hotkeys.git", exit code of #128 fatal: 无法访问 'https://github.com/chieffancypants/angular-hotkeys.git/'：LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443

Additional error details:
fatal: 无法访问 'https://github.com/chieffancypants/angular-hotkeys.git/'：LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443
✖ Install fail! RunScriptError: Run "sh -c bower install --allow-root && not-in-install && gulp build || in-install" error, exit code 1
RunScriptError: Run "sh -c bower install --allow-root && not-in-install && gulp build || in-install" error, exit code 1
    at ChildProcess.proc.on.code (/Users/oxx/.nvm/versions/node/v8.12.0/lib/node_modules/cnpm/node_modules/runscript/index.js:96:21)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
npminstall version: 3.28.0
npminstall args: /Users/oxx/.nvm/versions/node/v8.12.0/bin/node /Users/oxx/.nvm/versions/node/v8.12.0/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js --fix-bug-versions --china --userconfig=/Users/oxx/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://registry.nlark.com

使用cnpm install 和npm install 安装失败
使用vpn 并在命令行开启代理

是我的vpn环境导致的吗？

**Comment by SuperChaoM** [comment]
解决了
github添加ssh key
恢复git://
git config --global url."git@github.com:".insteadOf https://github.com/
git config --global url."git://".insteadOf https://

**Comment by SuperChaoM** [comment]
解决了
